#John Dave L. Maca

###3rd Quarter Exam : Solving Systems of Equations Using Matrix Inverse

#Part 1: Theory

In [29]:
import numpy as np

# Step 1: Define the matrix A (5x5) and vector B (5x1)
A = np.array([[3, 2, -1, 0, 0],
              [2, -1, 3, 0, 0],
              [1, 2, 4, 3, 0],
              [0, 1, -2, 2, 1],
              [0, 0, 3, 1, 4]])

B = np.array([1, 2, 3, 4, 5])

# Step 2: Calculate the inverse of matrix A
A_inv = np.linalg.inv(A)

# Step 3: Calculate the solution vector X
X = np.dot(A_inv, B)

# Step 4: Display the solution
print("The solution vector X is:")
print(X)

The solution vector X is:
[ 0.9057971  -0.99275362 -0.26811594  1.7173913   1.02173913]


#Part 2: Application to Real-World Computer Science Problem

In [30]:
# Step 1: Define the coefficient matrix A (5x5) and the constant vector B (5x1)
A = np.array([[3, 2, 1, 1, 0],
              [1, 4, 2, 0, 1],
              [2, 3, 4, 1, 0],
              [1, 1, 3, 5, 0],
              [0, 1, 2, 4, 3]])

B = np.array([100, 150, 120, 110, 140])

# Step 2: Calculate the inverse of matrix A
A_inv = np.linalg.inv(A)

# Step 3: Calculate the solution vector X (the data flows between servers)
X = np.dot(A_inv, B)

# Step 4: Display the solution
print("The data flow between the servers (x1, x2, x3, x4, x5) is:")
print(X)

The data flow between the servers (x1, x2, x3, x4, x5) is:
[ 7.36462094 32.23826715 -1.62454874 15.05415162 16.93140794]


#Part 3: Step-by-Step Instructions

In [31]:
# Importing the necessary library
import numpy as np

# Coefficient matrix A (5x5 matrix)
A = np.array([
    [3, 2, 1, 1, 0],
    [1, 4, 2, 0, 1],
    [2, 3, 4, 1, 0],
    [1, 1, 3, 5, 0],
    [0, 1, 2, 4, 3]
])

# Constant matrix B (5x1 matrix)
B = np.array([100, 150, 120, 110, 140])

# Checking if matrix A is invertible (determinant should not be zero)
det_A = np.linalg.det(A)
if det_A == 0:
    print("Matrix A is singular and cannot be inverted!")
else:
    # Finding the inverse of matrix A
    A_inv = np.linalg.inv(A)

    # Solving for X using the matrix inverse method
    X = np.dot(A_inv, B)

    print("Solution (Unknowns):")
    print(X)

Solution (Unknowns):
[ 7.36462094 32.23826715 -1.62454874 15.05415162 16.93140794]


#Part 4: Practice Problems

##Problem 1

In [32]:
import numpy as np

A = np.array([
    [2, 1, -1],
    [-1, 3, 2],
    [1, -2, 4],

])

B = np.array([5, 6, 7])

det_A = np.linalg.det(A)
if det_A == 0:
    print("Matrix A is singular and cannot be inverted!")
else:
    # Finding the inverse of matrix A
    A_inv = np.linalg.inv(A)

    # Solving for X using the matrix inverse method
    X = np.dot(A_inv, B)

    print("Solution (Unknowns):")
    print(X)

Solution (Unknowns):
[2.64102564 1.61538462 1.8974359 ]


##Problem 2

In [33]:
import numpy as np

A = np.array([
    [5, 3, 1, 1, 0],
    [4, 6, 2, 0, 1],
    [2, 7, 3, 1, 0],
    [1, 2, 4, 5, 0],
    [3, 4, 5, 0, 6]
])

B = np.array([200, 300, 150, 120, 250])

det_A = np.linalg.det(A)
if det_A == 0:
    print("Matrix A is singular and cannot be inverted!")
else:
    # Finding the inverse of matrix A
    A_inv = np.linalg.inv(A)

    # Solving for X using the matrix inverse method
    X = np.dot(A_inv, B)

    print("Solution (Unknowns):")
    print(X)

Solution (Unknowns):
[ -23.86666667  137.6        -336.          242.53333333  241.86666667]


##Problem 3

In [34]:
import numpy as np
import numpy.linalg as LA

A = np.array([[2, 1, 0, 0, 0, 0, 0],
             [1, 2, 1, 0, 0, 0, 0],
             [0, 1, 2, 1, 0, 0, 0],
             [0, 0, 1, 2, 1, 0, 0],
             [0, 0, 1, 2, 2, 0, 0],
             [0, 0, 0, 1, 2, 1, 0],
             [0, 0, 0, 0, 1, 2, 1]])

b = np.array([5, 6, 7, 8, 9, 10, 11])

# Calculate the inverse of A
A_inv = LA.inv(A)

# Solve for x
x = np.dot(A_inv, b)
print("The unknown variables are:", x)

The unknown variables are: [ 1.8  1.4  1.4  2.8  1.   5.2 -0.4]


##Problem 4

In [35]:
import numpy as np

# Coefficient matrix A
A = np.array([
    [2, 1, -1, 0, 0],
    [-1, 3, 2, 0, 0],
    [1, -2, 4, 0, 0],
    [1, 1, 1, 1, 1],
    [2, 3, 1, 2, 1]
])

# Constant matrix B
B = np.array([10, 5, 12, 20, 30])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X (the unknown variables)
X = np.dot(A_inv, B)

print("Values of the unknowns (x1, x2, x3, x4, x5):")
print(X)

Values of the unknowns (x1, x2, x3, x4, x5):
[5.38461538 1.76923077 2.53846154 1.07692308 9.23076923]


##Problem 5

In [36]:
import numpy as np

def solve_linear_system(A, B):
    try:
        U, S, V = np.linalg.svd(A)
        A_pinv = np.linalg.pinv(A)

        X = np.dot(A_pinv, B)
        print("The unknown variables are:", X)
        return X
    except np.linalg.LinAlgError:
        print("Matrix is singular or ill-conditioned!")
        return None

##Funtion Test 1


In [37]:
import numpy as np

A = np.array([
    [1, 2, 3, 4],
    [2, -1, 1, 2],
    [3, 1, -1, -1],
    [1, 0, 2, 3]
])

B = np.array([14, 8, 5, 13])


solution = solve_linear_system(A, B)

if solution is not None:
    print("Solution (x1, x2, x3, x4):", solution)

The unknown variables are: [2.38562753 0.53744939 1.16093117 1.99493927]
Solution (x1, x2, x3, x4): [2.38562753 0.53744939 1.16093117 1.99493927]


##Function Test 2

In [38]:
import numpy as np

A = np.array([
    [2, 1, -1],
    [-3, 2, 1],
    [1, -2, 4]
])

B = np.array([8, -11, 13])

solution = solve_linear_system(A, B)

if solution is not None:
    print("Solution (x1, x2, x3):", solution)

The unknown variables are: [4.86206897 0.62068966 2.34482759]
Solution (x1, x2, x3): [4.86206897 0.62068966 2.34482759]
