<a href="https://colab.research.google.com/github/Bochok24/Matrix/blob/main/Final_Exam_Matrix_CS_Maca.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix Generation


In [1]:
import numpy as np

# Step 1: Generate a 3x4 random matrix
matrix_3x4 = np.random.randint(1, 21, size=(3, 4))  # Adjust range as needed
A = matrix_3x4[:, :3]  # Coefficient matrix (first 3 columns)
b = matrix_3x4[:, 3]   # Right-hand side vector (last column)

print("Generated 3x4 Matrix:")
print(matrix_3x4)
print("\nCoefficient Matrix (A):")
print(A)
print("\nRight-hand Side Vector (b):")
print(b)

Generated 3x4 Matrix:
[[ 5 17 20 11]
 [20  1 17 17]
 [19 11  4  5]]

Coefficient Matrix (A):
[[ 5 17 20]
 [20  1 17]
 [19 11  4]]

Right-hand Side Vector (b):
[11 17  5]


#Verification

In [2]:
# Solve using Matrix Inverse Method
try:
    A_inv = np.linalg.inv(A)  # Compute A^-1
    x_manual = np.dot(A_inv, b)  # x = A^-1 * b
    print("\nSolution using Matrix Inverse Method:")
    print(x_manual)
except np.linalg.LinAlgError:
    print("\nMatrix A is singular and cannot be inverted.")

# Solve using Gaussian Elimination
x_gaussian = np.linalg.solve(A, b)  # Direct Gaussian elimination
print("\nSolution using Gaussian Elimination (NumPy):")
print(x_gaussian)

# Verify the solution
b_check = np.dot(A, x_gaussian)  # Recompute b using A and the computed x
print("\nVerification (Ax = b):")
print(b_check)


Solution using Matrix Inverse Method:
[ 0.26478718 -0.25870647  0.7037037 ]

Solution using Gaussian Elimination (NumPy):
[ 0.26478718 -0.25870647  0.7037037 ]

Verification (Ax = b):
[11. 17.  5.]
