<a href="https://colab.research.google.com/github/Bochok24/Matrix/blob/main/Gaussian_Activity_Maca.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Plate-Gauss Elimination

In [1]:
import numpy as np

# Function to perform Naïve Gaussian Elimination
def gaussian_elimination(A, b):
    n = len(b)
    # Forward elimination
    for i in range(n):
        # Make the diagonal contain all 1s
        for j in range(i + 1, n):
            factor = A[j][i] / A[i][i]
            A[j] = A[j] - factor * A[i]
            b[j] = b[j] - factor * b[i]
    return A, b

## Problem 1: Naive Gauss Elimination

In [2]:
A1 = np.array([[4, 1, -1], [5, 1, 2], [6, 1, 1]], dtype=float)
b1 = np.array([-2, 4, 6], dtype=float)

# Solve the system
A1_reduced, b1_reduced = gaussian_elimination(A1.copy(), b1.copy())
print("Reduced Matrix A:\n", A1_reduced)
print("Reduced Matrix b:\n", b1_reduced)

Reduced Matrix A:
 [[ 4.    1.   -1.  ]
 [ 0.   -0.25  3.25]
 [ 0.    0.   -4.  ]]
Reduced Matrix b:
 [-2.   6.5 -4. ]


##Problem 2: Naive Gauss Elimination with chopping to 4 significant digits

In [6]:
def chop(value, significant_digits):
    factor = 10 ** significant_digits
    return np.floor(value * factor) / factor

def gaussian_elimination_chopped(A, b, significant_digits):# Solve the system with chopping
    n = len(b)
    for i in range(n):
        for j in range(i + 1, n):
            factor = chop(A[j][i] / A[i][i], significant_digits)
            A[j] = A[j] - factor * A[i]
            b[j] = chop(b[j] - factor * b[i], significant_digits)
    return A, b

A2 = np.array([[4, 1, -1], [5, 1, 2], [6, 1, 1]], dtype=float)
b2 = np.array([-2, 4, 6], dtype=float)

A2_reduced, b2_reduced = gaussian_elimination_chopped(A2.copy(), b2.copy(), 4)
print("Chopped Reduced Matrix A:\n", A2_reduced)
print("Chopped Reduced Matrix b:\n", b2_reduced)

Chopped Reduced Matrix A:
 [[ 4.    1.   -1.  ]
 [ 0.   -0.25  3.25]
 [ 0.    0.   -4.  ]]
Chopped Reduced Matrix b:
 [-2.   6.5 -4. ]


##Problem 3: Determinant using Forward Elimination

In [8]:
def determinant(A):
    n = len(A)
    det = 1
    for i in range(n):
        det *= A[i][i]
    return det

A3 = np.array([[5, -1, 5], [-3, 2.099, 6], [10, -7, 0]], dtype=float)
A3_reduced, _ = gaussian_elimination(A3.copy(), np.zeros(A3.shape[0]))
det_A3 = determinant(A3_reduced)
print("Determinant of A3:", det_A3)

Determinant of A3: 150.05


##Problem 4: Determinant of a Given Matrix after Forward Elimination

In [11]:
def gaussian_elimination(A, b):
    n = len(b)
    # Forward elimination
    for i in range(n):
        # Make the diagonal contain all 1s
        for j in range(i + 1, n):
            factor = A[j][i] / A[i][i]
            A[j] = A[j] - factor * A[i]
            b[j] = b[j] - factor * b[i]
    return A, b

def determinant(A):
    """
    Calculates the determinant of a matrix after Gaussian elimination.

    Handles the case where the matrix becomes singular during elimination.
    """
    n = len(A)

    # Check if any diagonal element is zero after elimination
    if any(A[i][i] == 0 for i in range(n)):
        print("Matrix is singular after elimination. Determinant is 0.")
        return 0

    det = 1
    for i in range(n):
        det *= A[i][i]
    return det

# Given matrix A and its reduced form B
A = np.array([[25, 5, 1], [64, -4.8, 1], [144, 0.7, 1]], dtype=float)
b = np.array([0, 0, 0], dtype=float)  # Assuming b is a zero vector

# Perform Gaussian elimination
A_reduced, _ = gaussian_elimination(A.copy(), b.copy())

# Calculate determinant
det_A = determinant(A_reduced)
print("Determinant of A:", det_A)

Determinant of A: 998.5


##Problem 5: Gaussian Elimination with Partial Pivoting

In [12]:
def gaussian_elimination_partial_pivoting(A, b):
    """
    Solves a system of linear equations using Gaussian elimination with partial pivoting.

    Args:
        A: The coefficient matrix.
        b: The constant vector.

    Returns:
        x: The solution vector.
    """
    n = len(b)

    # Forward elimination with partial pivoting
    for i in range(n):
        # Find the pivot row
        pivot_row = i
        for j in range(i + 1, n):
            if abs(A[j][i]) > abs(A[pivot_row][i]):
                pivot_row = j

        # Swap rows if necessary
        if pivot_row != i:
            A[[i, pivot_row]] = A[[pivot_row, i]]
            b[[i, pivot_row]] = b[[pivot_row, i]]

        # Eliminate elements below the pivot
        for j in range(i + 1, n):
            factor = A[j][i] / A[i][i]
            A[j] = A[j] - factor * A[i]
            b[j] = b[j] - factor * b[i]

    # Back substitution
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i][i + 1:], x[i + 1:])) / A[i][i]

    return x

# Given system of equations
A = np.array([[4, 1, -1], [5, 1, 2], [6, 1, 1]], dtype=float)
b = np.array([-2, 4, 6], dtype=float)

# Solve using Gaussian elimination with partial pivoting
x = gaussian_elimination_partial_pivoting(A.copy(), b.copy())

print("Solution:")
print(x)

Solution:
[  3. -13.   1.]


##Problem 6: Gaussian Elimination with Partial Pivoting and Chopping

In [13]:
def chop(value, significant_digits):
    """Chops a value to the specified number of significant digits."""
    factor = 10 ** significant_digits
    return np.floor(value * factor) / factor

def gaussian_elimination_partial_pivoting_chopped(A, b, significant_digits):
    """
    Solves a system of linear equations using Gaussian elimination with partial pivoting
    and chopping to the specified number of significant digits.

    Args:
        A: The coefficient matrix.
        b: The constant vector.
        significant_digits: The number of significant digits to chop to.

    Returns:
        x: The solution vector.
    """
    n = len(b)

    # Forward elimination with partial pivoting
    for i in range(n):
        # Find the pivot row
        pivot_row = i
        for j in range(i + 1, n):
            if abs(A[j][i]) > abs(A[pivot_row][i]):
                pivot_row = j

        # Swap rows if necessary
        if pivot_row != i:
            A[[i, pivot_row]] = A[[pivot_row, i]]
            b[[i, pivot_row]] = b[[pivot_row, i]]

        # Eliminate elements below the pivot
        for j in range(i + 1, n):
            factor = chop(A[j][i] / A[i][i], significant_digits)  # Chop the factor
            A[j] = A[j] - factor * A[i]
            for k in range(len(A[j])):
                A[j][k] = chop(A[j][k], significant_digits)
            b[j] = chop(b[j] - factor * b[i], significant_digits) # Chop the result


    # Back substitution
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = chop((b[i] - np.dot(A[i][i + 1:], x[i + 1:])) / A[i][i], significant_digits)  # Chop the result

    return x

# Given system of equations
A = np.array([[4, 1, -1], [5, 1, 2], [6, 1, 1]], dtype=float)
b = np.array([-2, 4, 6], dtype=float)

# Solve using Gaussian elimination with partial pivoting and chopping
x = gaussian_elimination_partial_pivoting_chopped(A.copy(), b.copy(), 4)

print("Solution with chopping:")
print(x)

Solution with chopping:
[  3.0002 -13.0004   0.9992]
