<a href="https://colab.research.google.com/github/Bochok24/Matrix/blob/main/Matrix_Inverse_and_System_of_Equations_Maca.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Practice Problems
#Problem 1:

In [6]:
import numpy as np

# Define a 2x2 matrix
A = np.array([[3, 4],
              [2, 5]])

# Check if the matrix is invertible
det_A = np.linalg.det(A)
print("Problem 1:")
print(f"Determinant of A: {det_A}")

if det_A != 0:
    # Calculate the inverse
    A_inv = np.linalg.inv(A)
    print("Inverse of A:")
    print(A_inv)
else:
    print("Matrix A is not invertible.")

Problem 1:
Determinant of A: 7.000000000000001
Inverse of A:
[[ 0.71428571 -0.57142857]
 [-0.28571429  0.42857143]]


##Problem 2:

In [8]:
# Coefficient matrix A
A = np.array([[2, 3],
              [4, -1]])

# Constant vector b
b = np.array([7, 5])

# Solve for x using matrix inverse
if np.linalg.det(A) != 0:
    x = np.linalg.inv(A).dot(b)
    print("Solution for [x, y]:")
    print(x)
else:
    print("Matrix A is not invertible, no unique solution.")

Solution for [x, y]:
[1.57142857 1.28571429]


##Problem 3:

In [10]:
# Define the matrix A
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

# Check if the matrix is invertible
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A}")

if det_A != 0:
    # Calculate the inverse
    A_inv = np.linalg.inv(A)
    print("Inverse of A:")
    print(A_inv)
else:
    print("Matrix A is not invertible.")

Determinant of A: 0.9999999999999964
Inverse of A:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


##Problem 4:

In [17]:
# Define matrix A and vector B
A = np.array([[1, 1, 1],
              [2, 5, 1],
              [2, 3, 8]])

B = np.array([6,-4,9])

# Check if the matrix is invertible
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A}")

if det_A != 0:
    # Calculate the inverse
    A_inv = np.linalg.inv(A)
    # Solve for X
    X = np.dot(A_inv, B)
    print("Solution (x, y, z):")
    print(X)
else:
    print("Matrix A is not invertible.")

Determinant of A: 18.999999999999996
Solution (x, y, z):
[10.84210526 -5.21052632  0.36842105]


##Problem 5:

In [19]:
# Define matrix A and vector b
A = np.array([[4, -1, 0],
              [3, 5, 2],
              [-2, 4, 1]])

b = np.array([5,6,2])

# Check if the matrix is invertible
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A}")

if det_A != 0:
    # Calculate the inverse
    A_inv = np.linalg.inv(A)
    # Solve for x
    x = np.dot(A_inv, b)
    print("Solution (x, y, z):")
    print(x)
else:
    print("Matrix A is not invertible.")

Determinant of A: -5.000000000000002
Solution (x, y, z):
[  2.6   5.4 -14.4]


##Bonus Challenge

In [21]:
def check_and_inverse(matrix):
    """
    Check if the given n x n matrix is invertible and return its inverse if it is.

    Parameters:
    matrix (np.ndarray): An n x n matrix.

    Returns:
    np.ndarray or None: Inverse of the matrix if it is invertible, None otherwise.
    """
    # Check if the input is a square matrix
    if matrix.ndim != 2 or matrix.shape[0] != matrix.shape[1]:
        print("The matrix is not square, and therefore not invertible.")
        return None

    # Calculate the determinant
    det = np.linalg.det(matrix)
    print(f"Determinant: {det}")

    if det != 0:
        # If the determinant is non-zero, the matrix is invertible
        inverse_matrix = np.linalg.inv(matrix)
        return inverse_matrix
    else:
        # If the determinant is zero, the matrix is not invertible
        print("The matrix is not invertible.")
        return None

##Example Usage:

In [22]:
A = np.array([[4, -1, 0],
              [3, 5, 2],
              [-2, 4, 1]])

inverse_A = check_and_inverse(A)

if inverse_A is not None:
    print("Inverse of the matrix:")
    print(inverse_A)

Determinant: -5.000000000000002
Inverse of the matrix:
[[ 0.6 -0.2  0.4]
 [ 1.4 -0.8  1.6]
 [-4.4  2.8 -4.6]]
