<a href="https://colab.research.google.com/github/Bochok24/Matrix/blob/main/Matrix_Unary_Computations_Maca.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Q1: What are some examples of unary operations in matrices?

##Unary Operations on Matrices

###1. Transposition
The transpose of a matrix is obtained by flipping it over its diagonal, turning rows into columns and vice versa.

In [2]:
import numpy as np

# Create a sample matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose the matrix
transposed_matrix = matrix.T

print("Original Matrix:\n", matrix)
print("\nTransposed Matrix:\n", transposed_matrix)

Original Matrix:
 [[1 2 3]
 [4 5 6]]

Transposed Matrix:
 [[1 4]
 [2 5]
 [3 6]]


###2. Negation

Negating a matrix means multiplying each element by -1.

In [3]:
# Negate the matrix
negated_matrix = -matrix

print("\nNegated Matrix:\n", negated_matrix)


Negated Matrix:
 [[-1 -2 -3]
 [-4 -5 -6]]


###3. Determinant

The determinant is a scalar value that can be computed from a square matrix and provides important properties of the matrix.

In [4]:
square_matrix = np.array([[1, 2], [3, 4]])

# Calculate the determinant
determinant_value = np.linalg.det(square_matrix)

print("\nSquare Matrix:\n", square_matrix)
print("\nDeterminant of the square matrix:", determinant_value)


Square Matrix:
 [[1 2]
 [3 4]]

Determinant of the square matrix: -2.0000000000000004


###4. Matrix Norm

The norm of a matrix is a measure of its size or length. Common norms include the Frobenius norm.

In [5]:
# Calculate Frobenius norm
frobenius_norm = np.linalg.norm(matrix)

print("\nFrobenius Norm of the original matrix:", frobenius_norm)


Frobenius Norm of the original matrix: 9.539392014169456


###5. Inversion

The inverse of a matrix is another matrix such that when multiplied together, they yield the identity matrix. This operation is only applicable to square matrices that are non-singular.

In [6]:
# Invert the square matrix
inverse_matrix = np.linalg.inv(square_matrix)

print("\nInverse of the square matrix:\n", inverse_matrix)


Inverse of the square matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


###6. Trace

The trace of a square matrix is the sum of the elements on its main diagonal.

In [7]:
# Calculate the trace of the square matrix
trace_value = np.trace(square_matrix)

print("\nTrace of the square matrix:", trace_value)


Trace of the square matrix: 5


#Q2: Check if matrix_A is a symmetric matrix. Modify the code below to verify this.

In [9]:
matrix_A = np.array([[10, 20, 30],
                      [20, 50, 60],  # Changed to make it symmetric
                      [30, 60, 90]])

# Check if the matrix is symmetric
is_symmetric = (matrix_A == matrix_A.T).all()
print("\nIs Matrix A symmetric?:", is_symmetric)


Is Matrix A symmetric?: True


#Practice Problem 1:

In [1]:
# Create a 4x4 random matrix with values between 1 and 10
random_matrix = np.random.randint(1, 10, (4, 4))

# Create the transpose of the random matrix
transpose_random = random_matrix.T

# Check symmetry by comparing the matrix with its transpose
is_symmetric_random = (random_matrix == transpose_random).all()

# Print the results
print("Random Matrix:\n", random_matrix)
print("\nIs the random matrix symmetric?:", is_symmetric_random)

Random Matrix:
 [[5 6 1 1]
 [5 4 7 7]
 [8 2 7 4]
 [9 7 7 9]]

Is the random matrix symmetric?: False


#Q3: What is the trace of the following matrix?

In [8]:
matrix_A = np.array([[10, 20, 30],
                      [5, 15, 25],
                      [2, 4, 6]])

# Calculate the trace of matrix A
trace_A = np.trace(matrix_A)
print("\nTrace of Matrix A:", trace_A)


Trace of Matrix A: 31


#Practice Problem 2:

In [10]:
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Calculate the trace of the identity matrix
trace_identity = np.trace(identity_matrix)

print("Trace of the 5x5 identity matrix:", trace_identity)

Trace of the 5x5 identity matrix: 5.0


#Practice Problem 3:

In [15]:
# Define the 3x3 matrix D
matrix_D = np.array([[1, 2, 3],
                      [0, 4, 5],
                      [1, 0, 6]])

# Calculate the determinant of matrix D
det_D = np.linalg.det(matrix_D)
print("Determinant of Matrix D:", det_D)

Determinant of Matrix D: 22.000000000000004


##Manual Cofactor Method

In [16]:
# Define the 3x3 matrix A
matrix_A = np.array([[1, 2, 3],
                      [0, 4, 5],
                      [1, 0, 6]])

# Function to calculate the determinant using the cofactor method
def determinant_3x3(matrix):
    # Extracting elements of the first row
    a, b, c = matrix[0]

    # Calculate the determinant using cofactors
    det = (a * (matrix[1, 1] * matrix[2, 2] - matrix[1, 2] * matrix[2, 1]) -
           b * (matrix[1, 0] * matrix[2, 2] - matrix[1, 2] * matrix[2, 0]) +
           c * (matrix[1, 0] * matrix[2, 1] - matrix[1, 1] * matrix[2, 0]))
    return det

# Calculate the determinant of matrix A
det_A = determinant_3x3(matrix_A)
print("Determinant of Matrix A using cofactor method:", det_A)

Determinant of Matrix A using cofactor method: 22


#Practice Problem 4: Application in Computer Science

In [17]:
# Generate a random 3x3 matrix representing pixel intensities
# Pixel intensities between 0 and 255 (common for grayscale images)
matrix_pixel_intensities = np.random.randint(0, 256, (3, 3))

# Calculate the transpose of the matrix
transpose_matrix = np.transpose(matrix_pixel_intensities)

# Calculate the determinant of the matrix
determinant_matrix = np.linalg.det(matrix_pixel_intensities)

# Display the results
print("Original 3x3 Matrix (Pixel Intensities):")
print(matrix_pixel_intensities)
print("\nTranspose of the Matrix:")
print(transpose_matrix)
print("\nDeterminant of the Matrix:", determinant_matrix)

Original 3x3 Matrix (Pixel Intensities):
[[244 209 186]
 [117 212 137]
 [ 64 179  41]]

Transpose of the Matrix:
[[244 117  64]
 [209 212 179]
 [186 137  41]]

Determinant of the Matrix: -1661075.0000000007


#Practice Problem 5: Symmetric Matrices in Machine Learning

In [18]:
# Create a random 3x3 matrix
matrix = np.random.randint(1, 10, (3, 3))

# Create a symmetric matrix by averaging the matrix with its transpose
symmetric_matrix = (matrix + matrix.T) / 2

# Verify properties
is_symmetric = np.array_equal(symmetric_matrix, symmetric_matrix.T)

# Display the results
print("Original 3x3 Matrix:")
print(matrix)
print("\nSymmetric Matrix:")
print(symmetric_matrix)
print("\nIs the matrix symmetric?", is_symmetric)

Original 3x3 Matrix:
[[3 8 9]
 [7 5 8]
 [5 6 8]]

Symmetric Matrix:
[[3.  7.5 7. ]
 [7.5 5.  7. ]
 [7.  7.  8. ]]

Is the matrix symmetric? True
