<a href="https://colab.research.google.com/github/Bochok24/Matrix/blob/main/Numpy_Activity_Maca.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Create a 2x3 matrix

In [1]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix A:")
print(A)

Matrix A:
[[1 2 3]
 [4 5 6]]


In [2]:
# 3x3 Zero Matrix
zero_matrix = np.zeros((3, 3))
print("Zero Matrix:")
print(zero_matrix)

# 3x3 Identity Matrix
identity_matrix = np.eye(3)
print("Identity Matrix:")
print(identity_matrix)

Zero Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#Define Two Matrices Of The Same Shape

In [3]:
B = np.array([[1, 2], [3, 4]])
C = np.array([[5, 6], [7, 8]])

# Matrix Addition
addition_result = B + C
print("B + C:")
print(addition_result)

# Matrix Subtraction
subtraction_result = B - C
print("B - C:")
print(subtraction_result)

B + C:
[[ 6  8]
 [10 12]]
B - C:
[[-4 -4]
 [-4 -4]]


#Exercise 1

In [4]:
B = np.array([[5, 6], [8, 7]])
C = np.array([[2, 1], [4, 2]])


addition_result = B + C
print("B + C:")
print(addition_result)

# Matrix Subtraction
subtraction_result = B - C
print("B - C:")
print(subtraction_result)

B + C:
[[ 7  7]
 [12  9]]
B - C:
[[3 5]
 [4 5]]


##Defining Matrices for Multiplication

In [5]:
D = np.array([[1, 2], [3, 4]])
E = np.array([[2, 0], [1, 2]])

# Matrix Multiplication
multiplication_result = np.dot(D, E)
print("D * E (Matrix Multiplication):")
print(multiplication_result)

D * E (Matrix Multiplication):
[[ 4  4]
 [10  8]]


#Exercise 2

In [6]:
# Define matrices for multiplication
D = np.array([[3, 7, 1], [2, 1,9]])
E = np.array([[5, 2], [1, 2],[6,4]])

# Matrix Multiplication
multiplication_result = np.dot(D, E)
print("D * E (Matrix Multiplication):")
print(multiplication_result)

D * E (Matrix Multiplication):
[[28 24]
 [65 42]]


##Defining Matrices for Multiplication

In [7]:
D = np.array([[3, 7, 1], [2, 1, 9]])
E = np.array([[5, 2, 1], [6, 4, 1]])  # Define E directly in the shape (2, 3)

# Element-wise Multiplication
elementwise_result = D * E
print("D * E (Element-wise Multiplication):")
print(elementwise_result)

D * E (Element-wise Multiplication):
[[15 14  1]
 [12  4  9]]


##Transpose of a Matrix

In [8]:
transpose_result = D.T
print("Transpose of D:")
print(transpose_result)

Transpose of D:
[[3 2]
 [7 1]
 [1 9]]


#Exercise 3: Matrix Transpose

In [9]:
d = np.array([[1, 2, 3], [4, 5, 6]])


transpose_matrix = d.T
print("Original Matrix (2x3):")
print(d)
print("\nTranspose of the Matrix (3x2):")
print(transpose_matrix)

Original Matrix (2x3):
[[1 2 3]
 [4 5 6]]

Transpose of the Matrix (3x2):
[[1 4]
 [2 5]
 [3 6]]


##Define a 2x2 Square Matrix

In [10]:
F = np.array([[4, 2], [3, 1]])

# Determinant of F
determinant_result = np.linalg.det(F)
print("Determinant of F:", determinant_result)

Determinant of F: -2.0


#Exercise 4: Calculating the Determinant

In [11]:
F = np.array([[9, 8, 3], [2, 1, 6],[8,6,7]])

determinant_result = np.linalg.det(F)
print("Determinant of F:", determinant_result)

Determinant of F: 22.99999999999998


##Matrix Inverse

In [12]:
# Define an invertible 2x2 matrix
G = np.array([[4, 7], [2, 6]])

# Inverse of G
inverse_result = np.linalg.inv(G)
print("Inverse of G:")
print(inverse_result)

Inverse of G:
[[ 0.6 -0.7]
 [-0.2  0.4]]


#Exercise 5: Finding the Inverse

In [13]:
matrix = np.array([[4, 7, 2],
                   [3, 6, 1],
                   [2, 5, 9]])

# Calculate the inverse of the matrix
inverse_result = np.linalg.inv(matrix)

# Print the inverse
print("Inverse of the matrix:")
print(inverse_result)

Inverse of the matrix:
[[ 1.81481481 -1.96296296 -0.18518519]
 [-0.92592593  1.18518519  0.07407407]
 [ 0.11111111 -0.22222222  0.11111111]]


##Additional Challenge

In [14]:
A = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

B = [
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
]


result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]


for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]


print("Result of matrix multiplication:")
for row in result:
    print(row)

Result of matrix multiplication:
[30, 24, 18]
[84, 69, 54]
[138, 114, 90]


##Generating a Random 10×1010 \times 1010×10 Matrix and Performing Basic Operations

In [15]:
# Generate a random 10x10 matrix
random_matrix_A = np.random.rand(10, 10)
print("Random 10x10 Matrix A:")
print(random_matrix_A)

Random 10x10 Matrix A:
[[0.26382135 0.68692423 0.19947968 0.02938556 0.12283775 0.34947919
  0.7005549  0.04663721 0.38590071 0.73565565]
 [0.69385011 0.44109629 0.42441164 0.25292624 0.22909267 0.09458917
  0.67061871 0.79458836 0.31465117 0.36353982]
 [0.03641995 0.16777843 0.32063095 0.45789427 0.14282887 0.44364591
  0.75618949 0.80379302 0.82171523 0.07875512]
 [0.798072   0.6634429  0.9640776  0.64018426 0.42088204 0.89669013
  0.72327428 0.42960974 0.45316108 0.3964383 ]
 [0.91094875 0.57652964 0.4770901  0.85227571 0.54332086 0.71987346
  0.14840844 0.78219266 0.82304574 0.73852658]
 [0.0472367  0.09640818 0.47328648 0.02101591 0.55534281 0.18947463
  0.57827649 0.11736957 0.55167197 0.11280229]
 [0.67338937 0.40629526 0.45964849 0.35338696 0.65473782 0.71551016
  0.1987423  0.11044968 0.76292079 0.03998361]
 [0.62875046 0.01143096 0.84321449 0.85953437 0.50921779 0.5041182
  0.54075316 0.70409832 0.77559102 0.34964435]
 [0.52748317 0.90520925 0.11371729 0.07883938 0.22074122 0

#Creating Another Random Matrix of the Same Size

##Generate a Second Random 10x10 Matrix

In [16]:
random_matrix_B = np.random.rand(10, 10)
print("\nRandom 10x10 Matrix B:")
print(random_matrix_B)


Random 10x10 Matrix B:
[[0.72306917 0.12361791 0.46638063 0.95768251 0.67710533 0.59510915
  0.47430594 0.71905267 0.98858805 0.80086511]
 [0.4378445  0.69471308 0.71474114 0.90686227 0.97880886 0.84085841
  0.38224891 0.03436509 0.75679098 0.13574811]
 [0.92849098 0.16528019 0.60831589 0.84554225 0.02711644 0.33270557
  0.92712869 0.55010407 0.43405539 0.74008333]
 [0.92417983 0.30350067 0.76566459 0.73336086 0.49635421 0.13639255
  0.25733116 0.24950521 0.15291991 0.68236765]
 [0.04439922 0.56507831 0.94748443 0.429305   0.78851114 0.67809595
  0.77000679 0.820301   0.92533212 0.36387997]
 [0.03750289 0.4726577  0.74543715 0.43202108 0.1836313  0.24849381
  0.50189376 0.38345236 0.11477652 0.62642764]
 [0.42618463 0.54317191 0.65738008 0.76822575 0.72252779 0.53948891
  0.55691171 0.64057376 0.76691532 0.06798869]
 [0.0616091  0.53596728 0.21706989 0.61151567 0.8795434  0.34428915
  0.62041768 0.19497856 0.70923547 0.22473583]
 [0.21419909 0.71713048 0.72362566 0.11691918 0.54939351

##Matrix Addition

In [17]:
addition_result = random_matrix_A + random_matrix_B
print("\nA + B (Matrix Addition):")
print(addition_result)


A + B (Matrix Addition):
[[0.98689053 0.81054214 0.66586031 0.98706807 0.79994309 0.94458834
  1.17486084 0.76568988 1.37448876 1.53652076]
 [1.13169461 1.13580937 1.13915278 1.15978852 1.20790154 0.93544758
  1.05286763 0.82895345 1.07144216 0.49928793]
 [0.96491093 0.33305862 0.92894684 1.30343651 0.16994531 0.77635147
  1.68331818 1.35389709 1.25577062 0.81883846]
 [1.72225183 0.96694357 1.72974219 1.37354512 0.91723625 1.03308268
  0.98060545 0.67911495 0.60608099 1.07880594]
 [0.95534797 1.14160796 1.42457453 1.28158071 1.331832   1.39796941
  0.91841523 1.60249366 1.74837785 1.10240655]
 [0.08473959 0.56906588 1.21872363 0.45303699 0.73897411 0.43796844
  1.08017025 0.50082192 0.66644849 0.73922993]
 [1.099574   0.94946716 1.11702857 1.1216127  1.3772656  1.25499907
  0.75565401 0.75102344 1.52983611 0.10797229]
 [0.69035956 0.54739824 1.06028438 1.47105003 1.38876119 0.84840735
  1.16117084 0.89907688 1.48482649 0.57438018]
 [0.74168225 1.62233974 0.83734295 0.19575857 0.770134

##Matrix Subtraction

In [18]:
subtraction_result = random_matrix_A - random_matrix_B
print("\nA - B (Matrix Subtraction):")
print(subtraction_result)


A - B (Matrix Subtraction):
[[-0.45924782  0.56330632 -0.26690095 -0.92829695 -0.55426758 -0.24562997
   0.22624896 -0.67241545 -0.60268734 -0.06520947]
 [ 0.25600561 -0.25361679 -0.2903295  -0.65393603 -0.74971619 -0.74626924
   0.2883698   0.76022326 -0.44213981  0.22779171]
 [-0.89207103  0.00249823 -0.28768494 -0.38764798  0.11571242  0.11094034
  -0.1709392   0.25368896  0.38765984 -0.66132821]
 [-0.12610782  0.35994223  0.19841302 -0.0931766  -0.07547217  0.76029758
   0.46594312  0.18010454  0.30024118 -0.28592935]
 [ 0.86654953  0.01145133 -0.47039434  0.42297071 -0.24519029  0.0417775
  -0.62159835 -0.03810834 -0.10228638  0.37464661]
 [ 0.00973381 -0.37624952 -0.27215067 -0.41100517  0.37171152 -0.05901918
   0.07638273 -0.26608279  0.43689545 -0.51362535]
 [ 0.24720475 -0.13687665 -0.19773159 -0.41483879 -0.06778997  0.17602125
  -0.35816941 -0.53012408 -0.00399453 -0.02800508]
 [ 0.56714136 -0.52453632  0.6261446   0.2480187  -0.3703256   0.15982905
  -0.07966451  0.509119

##Matrix Multiplication

In [19]:
multiplication_result = np.dot(random_matrix_A, random_matrix_B)
print("\nA * B (Matrix Multiplication):")
print(multiplication_result)


A * B (Matrix Multiplication):
[[1.2160368  1.78395069 2.53709001 2.43256052 1.97475225 2.25621743
  1.86260743 1.74674719 2.16544046 1.29587801]
 [1.79262401 1.88491262 2.54170534 3.05832618 2.68359278 2.28422264
  2.41817484 2.09876346 2.84622032 1.82728355]
 [1.40318215 2.0680146  2.48462272 2.27445971 2.34337505 1.77269244
  2.30588375 2.09502857 1.90102549 1.91128946]
 [2.89742386 2.69290557 4.23845775 4.38705159 3.27850069 3.10791297
  3.60892092 3.15376931 3.50845776 3.22865027]
 [2.59050012 2.90460548 4.34900599 4.20982309 3.60930747 3.34256338
  3.53275319 3.27372192 3.57526567 3.46824495]
 [0.95563266 1.38177665 1.96722515 1.53357088 1.47457963 1.46812083
  1.82339856 1.81914168 1.56305604 1.31688394]
 [1.73495016 1.98829861 3.05051438 2.59073607 2.35902851 2.19042076
  2.53559437 2.56761348 2.30456408 2.58757565]
 [2.57043468 2.38911444 3.7103706  3.59087578 2.90383585 2.55244012
  3.34504059 3.15117331 2.94379107 3.17687179]
 [1.35205096 1.55029966 2.10014806 2.32087649 2.

In [20]:
# Transpose of random_matrix_A
transpose_result_A = random_matrix_A.T
print("\nTranspose of Matrix A:")
print(transpose_result_A)

# Transpose of random_matrix_B
transpose_result_B = random_matrix_B.T
print("\nTranspose of Matrix B:")
print(transpose_result_B)


Transpose of Matrix A:
[[0.26382135 0.69385011 0.03641995 0.798072   0.91094875 0.0472367
  0.67338937 0.62875046 0.52748317 0.76882599]
 [0.68692423 0.44109629 0.16777843 0.6634429  0.57652964 0.09640818
  0.40629526 0.01143096 0.90520925 0.20324741]
 [0.19947968 0.42441164 0.32063095 0.9640776  0.4770901  0.47328648
  0.45964849 0.84321449 0.11371729 0.2118291 ]
 [0.02938556 0.25292624 0.45789427 0.64018426 0.85227571 0.02101591
  0.35338696 0.85953437 0.07883938 0.33503133]
 [0.12283775 0.22909267 0.14282887 0.42088204 0.54332086 0.55534281
  0.65473782 0.50921779 0.22074122 0.78344927]
 [0.34947919 0.09458917 0.44364591 0.89669013 0.71987346 0.18947463
  0.71551016 0.5041182  0.10426386 0.79297805]
 [0.7005549  0.67061871 0.75618949 0.72327428 0.14840844 0.57827649
  0.1987423  0.54075316 0.715595   0.92336759]
 [0.04663721 0.79458836 0.80379302 0.42960974 0.78219266 0.11736957
  0.11044968 0.70409832 0.00975741 0.65547219]
 [0.38590071 0.31465117 0.82171523 0.45316108 0.82304574 

#Learning Assessment Questions

##1. Matrix Creation and Structure

A matrix is a rectangular array of numbers, symbols, or expressions arranged in rows and columns. Matrices are fundamental in linear algebra and are used in various fields such as physics, computer graphics, and machine learning. The size of a matrix is defined by the number of its rows and columns.

Sample Code:

In [21]:
k_3x23 = np.random.randint(1, 10,(3, 23))


k_23x2 = np.random.randint(1, 10,(23, 2))

print("3x23 Matrix:\n", k_3x23)
print("\n23x2 Matrix:\n", k_23x2)

3x23 Matrix:
 [[3 6 3 2 9 4 3 3 1 5 3 1 9 6 6 2 2 6 2 3 4 6 1]
 [6 8 5 8 4 9 6 5 7 2 6 1 1 6 1 9 3 6 1 2 2 8 4]
 [5 3 7 3 4 1 1 2 6 1 8 6 1 4 2 1 3 4 2 4 2 9 2]]

23x2 Matrix:
 [[6 1]
 [5 2]
 [1 9]
 [9 5]
 [2 9]
 [7 8]
 [2 5]
 [5 7]
 [6 4]
 [6 5]
 [3 7]
 [7 6]
 [7 9]
 [5 7]
 [2 7]
 [6 4]
 [5 8]
 [4 4]
 [7 1]
 [1 5]
 [9 5]
 [7 7]
 [6 2]]


##2. Basic Matrix Operations

For matrix addition, two matrices must have the same dimensions (same number of rows and columns). You add them by adding each matching element.

For matrix multiplication, the number of columns in the first matrix must equal the number of rows in the second. The result will have the same number of rows as the first matrix and the same number of columns as the second. Each element in the result is a dot product of a row from the first matrix and a column from the second.

Sample Code:

In [22]:
A = np.random.randint(1, 10,(5, 5))
B = np.random.randint(1, 10,(5, 5))


matrix_sum = A + B


matrix_product = np.dot(A, B)

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nMatrix Addition (A + B):\n", matrix_sum)
print("\nMatrix Multiplication (A * B):\n", matrix_product)

Matrix A:
 [[7 4 3 4 6]
 [3 7 6 6 5]
 [8 2 7 9 5]
 [8 7 5 1 4]
 [7 8 5 8 5]]

Matrix B:
 [[2 3 7 5 1]
 [3 1 5 5 2]
 [2 3 1 2 3]
 [6 7 6 1 9]
 [4 5 2 1 1]]

Matrix Addition (A + B):
 [[ 9  7 10  9  7]
 [ 6  8 11 11  7]
 [10  5  8 11  8]
 [14 14 11  2 13]
 [11 13  7  9  6]]

Matrix Multiplication (A * B):
 [[ 80  92 108  71  66]
 [ 95 101 108  73  94]
 [110 135 137  78 119]
 [ 69  73 110  90  50]
 [116 125 152  98 115]]


##3. Matrix Transposition

The transpose of a matrix is obtained by flipping it over its diagonal, which swaps its rows and columns. If a matrix has dimensions 𝑚 × 𝑛 m×n, its transpose will have dimensions 𝑛 × 𝑚

Sample Code:

In [23]:
k = np.random.randint(1, 10, (3, 2))


matrix_transpose = k.T

print("Original 3x2 Matrix:\n", matrix)
print("\nTranspose of the Matrix (2x3):\n", matrix_transpose)

Original 3x2 Matrix:
 [[4 7 2]
 [3 6 1]
 [2 5 9]]

Transpose of the Matrix (2x3):
 [[1 1 5]
 [5 9 7]]


##4. Working with Large Matrices

In [24]:
matrix = np.random.randint(1, 11, (5, 5))

matrix_sum = np.sum(matrix)


matrix_transpose = matrix.T

# Print the results
print("Original 5x5 Matrix:\n", matrix)
print("\nSum of all elements in the matrix:", matrix_sum)
print("\nTranspose of the Matrix:\n", matrix_transpose)

Original 5x5 Matrix:
 [[ 7 10  3  4  4]
 [ 7  4  8  4 10]
 [ 9  3 10  2  6]
 [ 9  9  7  2  4]
 [ 6  5  6  4  9]]

Sum of all elements in the matrix: 152

Transpose of the Matrix:
 [[ 7  7  9  9  6]
 [10  4  3  9  5]
 [ 3  8 10  7  6]
 [ 4  4  2  2  4]
 [ 4 10  6  4  9]]


##Answer:

If we want to make a random 5 × 5 5x5 matrix in NumPy, we can just write np.random.randint(1, 11, (5, 5)) because we want to generate a whole number between 1 and 10 for each element in the matrix. Next we can compute the sum of all elements of the matrix using np.sum(matrix). Finally, to get the transpose of the matrix we are using matrix.T, which flips the matrix across the diagonal, making rows into columns. This gives us the total of the matrix elements and it’s transposed form.

##Applying Matrix Operations in Context

Matrix Addition (D + E): Adds matching elements from both matrices. This can help in tasks like merging two images or increasing brightness.

Matrix Subtraction (D - E): Finds differences between two matrices. This is useful in detecting changes between images or video frames, such as movement.

Matrix Multiplication (D * E): Combines matrices in a way that’s essential for tasks in graphics (e.g., rotating objects) and machine learning calculations.

In [25]:
D = np.random.randint(1, 11, (10, 10))
E = np.random.randint(1, 11, (10, 10))


matrix_addition = D + E
print("Matrix Addition (D + E):\n", matrix_addition)


matrix_subtraction = D - E
print("\nMatrix Subtraction (D - E):\n", matrix_subtraction)


matrix_multiplication = np.dot(D, E)
print("\nMatrix Multiplication (D * E):\n", matrix_multiplication)

Matrix Addition (D + E):
 [[14 12 16  9 12  7  4  2  6  8]
 [10 17 12 10  5  5  7 10  6 17]
 [ 8 17 18  6  9 14 11  2 12 14]
 [15 11 10 13 10  4  2  3  9 11]
 [ 5  4 19 13  9  4 12 11  4  5]
 [18 12  6 12 10 18 14 16 15  9]
 [18 10  8  6 11 14  8 15 12 10]
 [12 13 11 13 17 10  6  4 11 14]
 [12 10 15 13  8 14  5  6 12 15]
 [16 17 13 13  8  7 11 14  4 15]]

Matrix Subtraction (D - E):
 [[ 2  0  0 -5  6  3  2  0  0  0]
 [ 2 -1  8 -4  3 -3 -1 -4  2 -3]
 [ 0 -1  2  2  1 -2 -7  0 -6  2]
 [-5 -3 -4 -5  8  2  0 -1 -7  5]
 [ 3 -2 -1 -3  1 -2 -4 -3  2 -3]
 [ 0 -6  0 -2  4  2  4  4  5 -5]
 [-2 -2  4  2  3  6  0 -1  8  0]
 [-4  1 -3 -3  1 -4 -2 -2  3  4]
 [ 2  8  5 -7  4 -4 -3  4  4 -1]
 [ 2  1 -1  5 -2 -5  7 -2 -2 -3]]

Matrix Multiplication (D * E):
 [[259 319 315 299 161 243 239 217 192 297]
 [274 336 304 282 167 258 222 205 212 321]
 [294 368 306 296 164 277 240 235 229 341]
 [213 252 269 250 134 173 167 201 140 237]
 [222 232 252 219 136 189 185 126 184 195]
 [459 394 389 467 251 368 279 280 